### ISSUE TITLE
BigQuery: Error 429: The object ... exceeded the rate limit for object mutation operations

### ISSUE THREAD

**Issue by eugen-korentsov** [pingcap-inc/tidb2dw#98]
Using latest version - https://github.com/pingcap-inc/tidb2dw/commit/b892f265e6c4cb02397e4b0fd14d834a035b093d

Still get error:
[snapshot.go:163] ["Failed to upload loadinfo"] [table=....] [error="googleapi: Error 429: The object .../loadinfo exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429., rateLimitExceeded"]

**Comment by eugen-korentsov** [comment]
More info, it is snapshot-only mode, I am dumping 24 tables
Like this:
```
tidb2dw bigquery --mode=snapshot-only --storage gs://tidb2dw/all-`date +%a` --table 1 --table 2 ... --table 24
```

**Comment by Lloyd-Pottiger** [comment]
@eugen-korentsov Thanks for feedback!
9af6c9f75e6de855018b774fa2c42bd657a723fa fix this issue.

Please try again with latest commit~
